#!/bin/sh

# This script recursively find and delete each file in the given search
# path with a access time older than 30 days. Then recursively find
# and delete empty directories in the given search path.
#
# This script is intended to be used as a maintenance tool to clean
# temporary files older than 30 days.

# WARNING: THIS SCRIPT FINDS AND DELETE ARBITRARY FILES IN THE GIVEN SEARCH
# PATH WITHOUT PROMPTING. USE WITH CAUTION!

search_path="tmp dir"
verbose="" #"-print"

# Swap the input field separator to deal with search path containing spaces
SAVEIFS=$IFS
IFS=$'\n'

echo ""
echo "  Cleaning old files in $search_path"

echo "  Removing Apple Directoy Store and Thumbnail Cache"
find $search_path -name ".DS_Store" -delete $verbose
find $search_path -name ".Trashes" -type d -delete $verbose
find $search_path -name ".Spotlight-v100" -type d -delete $verbose
#find $search_path -name ".DocumentRevisions-V100" -type d -delete $verbose
#find $search_path -name ".fseventsd" -type d -delete $verbose
find $search_path -name ".AppleDB" -type d -delete $verbose

echo "  Removing Windows Directoy Store and Thumbnail Cache"
find $search_path -name "Thumbs.db" -delete $verbose
find $search_path -name "RECYCLER" -type d -delete $verbose

echo "  Removing QNAS Thumbnail Cache"
find $search_path -name ".@__thumb" -type d -delete $verbose 

echo "  Removing Linux/Gnome Directoy Store and Thumbnail Cache"
find $search_path -name ".Trash-*" -type d -delete $verbose

echo "  Removing Partial Torrent files"
#find $search_path -name "*.!ut" -delete $verbose
#find $search_path -name "*.part" -delete $verbose

echo "  Removing empty folders"
find $search_path -type d -empty -delete $verbose




IFS=$SAVEIFS
